LOCAL_VIDEO_STATUS_IMPORT_REQUIRED = '待导入'
LOCAL_VIDEO_STATUS_ENRICH_REQUIRED = '待补全'
LOCAL_VIDEO_STATUS_RENAME_REQUIRED = '待重命名'
LOCAL_VIDEO_STATUS_NORMALIZED = '已规范'


LOCAL_VIDEO_PREVIEW_IMPORT_REQUIRED = '待导入数据库'
LOCAL_VIDEO_PREVIEW_ENRICH_REQUIRED = '数据库无标题，待补全'
